TABLE_SCHEMA = {
    "symbol": "TEXT PRIMARY KEY",
    "org_name_en": "TEXT",
    "main_operation_business": "TEXT",
    "org_cn_introduction": "TEXT",
    "chairman": "TEXT",
    "org_website": "TEXT",
    "reg_address_cn": "TEXT",
    "office_address_cn": "TEXT",
    "telephone": "TEXT",
    "postcode": "TEXT",
    "provincial_name": "TEXT",
    "staff_num": "INTEGER",
    "affiliate_industry": "TEXT",
    "operating_scope": "TEXT",
    "listed_date": "DATE",
    "org_name_cn": "TEXT",
    "org_short_name_cn": "TEXT",
    "org_short_name_en": "TEXT",
    "org_id": "TEXT",
    "established_date": "DATE",
    "actual_issue_vol": "INTEGER",
    "reg_asset": "REAL",
    "issue_price": "REAL",
    "currency": "TEXT"
}
